# Generated by Django 3.2.5 on 2021-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viec_lam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinhnghiem',
            name='ten',
            field=models.CharField(max_length=80),
        ),
    ]
