# Generated by Django 3.2.5 on 2021-09-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viec_lam_app', '0003_auto_20210925_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungvien',
            name='bang_cap',
            field=models.ManyToManyField(null=True, to='viec_lam_app.BangCap'),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='kinh_nghiem',
            field=models.ManyToManyField(null=True, to='viec_lam_app.KinhNghiem'),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='ky_nang',
            field=models.ManyToManyField(null=True, to='viec_lam_app.KyNang'),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='nganh_nghe',
            field=models.ManyToManyField(null=True, to='viec_lam_app.NganhNghe'),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='bang_cap',
            field=models.ManyToManyField(null=True, to='viec_lam_app.BangCap'),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='kinh_nghiem',
            field=models.ManyToManyField(null=True, to='viec_lam_app.KinhNghiem'),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='ky_nang',
            field=models.ManyToManyField(null=True, to='viec_lam_app.KyNang'),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='nganh_nghe',
            field=models.ManyToManyField(null=True, to='viec_lam_app.NganhNghe'),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='phuc_loi',
            field=models.ManyToManyField(null=True, to='viec_lam_app.PhucLoi'),
        ),
    ]
