# Generated by Django 3.2.5 on 2021-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viec_lam_app', '0004_auto_20210926_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatuyendung',
            name='gioi_thieu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='gioi_thieu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='noi_dung',
            field=models.TextField(),
        ),
    ]
