# Generated by Django 3.2.5 on 2021-09-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viec_lam_app', '0006_auto_20210927_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quanly',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ungvien',
            name='cv',
            field=models.FileField(null=True, upload_to='static/upload/%Y/%m'),
        ),
    ]
