# Generated by Django 3.2.5 on 2021-09-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viec_lam_app', '0007_auto_20210928_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatuyendung',
            name='gioi_thieu',
            field=models.TextField(blank=True, default=''),
        ),
    ]
