# Generated by Django 3.2.5 on 2021-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0002_remove_ungvien_diem_danh_gia_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='vieclam',
            name='luong',
            field=models.IntegerField(default=0),
        ),
    ]
