# Generated by Django 3.2.5 on 2021-09-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0004_alter_nhatuyendung_nguoi_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatuyendung',
            name='nguoi_dung',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
