# Generated by Django 3.2.5 on 2021-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0005_alter_nhatuyendung_nguoi_dung'),
    ]

    operations = [
        migrations.AddField(
            model_name='ungtuyen',
            name='nguoi_gui',
            field=models.CharField(choices=[('NTD', 'NTD gui loi moi lam viec cho UV'), ('UV', 'UV nop don ung tuyen')], default='UV', max_length=10),
        ),
    ]
