# Generated by Django 3.2.5 on 2021-09-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0006_ungtuyen_nguoi_gui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ungvien',
            name='chuc_danh',
        ),
    ]
