# Generated by Django 3.2.5 on 2021-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0007_remove_ungvien_chuc_danh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ungtuyen',
            name='nguoi_gui',
        ),
        migrations.AddField(
            model_name='ungtuyen',
            name='ung_vien_nop_don',
            field=models.BooleanField(default=True),
        ),
    ]
